#!/bin/bash -e

function usage() {
   echo "usage:" >&2
   echo "   pyv [ -r|--recreate | -u|--update ] script.py [args ...]" >&2
   echo >&2
   echo "Runs the python script at script.py using a local virtualenv" >&2
   echo "specified in script.pyv" >&2
   echo "The virtualenv will be created if needed."
   echo >&2
   echo "Options:" >&2
   echo "   -r: recreate virtualenv from scratch" >&2
   echo "       (default is to leave in place if it already exists)" >&2
   echo "   -u: update an existing virtualenv" >&2
   echo "       (default is to use as is if it already exists)" >&2
}

if [[ $# -lt 1 ]]; then
   usage
   exit 1
fi

if [[ "$1" == "-?" || "$1" == "-h" || "$1" == "-help" || "$1" == "--help" ]]; then
   usage
   exit 1
fi

if [[ "$1" == "-r" || "$1" == "--recreate" ]]; then
   recreate=1
   shift
fi

if [[ "$1" == "-u" || "$1" == "--update" ]]; then
   update=1
   shift
fi

script_name=$1
shift

script_dirname=$(dirname $script_name)
script_basename=$(basename $script_name)
venv_name=${script_basename%.py}
pyv_file=${script_dirname}/${venv_name}.pyv

if [[ ! -r $pyv_file ]]; then
   echo "ERROR: File not found $pyv_file" >&2
   echo >&2
   usage
   exit 1
fi

pyv_dir="${script_dirname}/.pyv"
venv_dir="${pyv_dir}/${venv_name}"

if [[ ! -r "$venv_dir/bin/activate" ]]; then
   recreate=1
fi

if [[ -n "$recreate" ]]; then
   if [[ -d $venv_dir ]]; then
      rm -f -r $venv_dir
   fi
   mkdir -p $pyv_dir
   # this will respect anything set by pyenv
   python=$(which python)
   virtualenv -p $python $venv_dir >&2
fi

if [[ ! -r "$venv_dir/bin/activate" ]]; then
   echo "ERROR: pyv venv not properly setup, possible pyv bug: $venv_dir" >&2
fi

. $venv_dir/bin/activate

if [[ -n "$recreate" || -n "$update" ]]; then
   pip install -r $pyv_file >&2
fi
   
# temporarily disable errexit (#!/bin/bash -e) so that we can cleanly deal with
# calling a script that might fail, and exitting with its exit value
set +o errexit
python $script_name "$@"
exitval=$?
set -o errexit

deactivate

exit $exitval
